version: '3.7'

services:
  api:
    build:
      context: ./packages/api
      target: development
      args:
        APP_PORT: "${API_PORT}"
    networks:
      - appnet
    volumes:
      - './packages/api:/app'
    ports:
      - "${API_PORT}:${API_PORT}"
      - "9229:9229"
    expose:
      - "${API_PORT}"
      - 9229
    depends_on:
      - mysql
      - frontend
  frontend:
    build:
      context: ./packages/frontend
      target: development
      args:
        APP_PORT: "${FRONTEND_PORT}"
    networks:
      - appnet
    volumes:
      - './packages/frontend:/app'
      - 'assets:/app/public/build'
    ports:
      - "${FRONTEND_PORT}:${FRONTEND_PORT}"
      - "9230:9230"
    expose:
      - "${FRONTEND_PORT}"
      - 9230
    depends_on:
      - ui
  ui:
    build:
      context: ./packages/ui
      target: development
      args:
        APP_PORT: "${UI_PORT}"
    networks:
      - appnet
    volumes:
      - './packages/ui/src:/app/src'
      - 'assets:/app/public/build'
    ports:
      - "${UI_PORT}:${UI_PORT}"
    expose:
      - "${UI_PORT}"
  mysql:
    image: mysql:5.7
    networks:
      - appnet
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "--silent"]
    environment:
      MYSQL_DATABASE: 'test'
      MYSQL_USER: 'test'
      MYSQL_PASSWORD: 'test'
      MYSQL_ROOT_PASSWORD: 'test'
    ports:
      - '3306:3306'
networks:
  appnet:
volumes:
  assets:
